CREATE TABLE halloween2018( id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, steam_id VARCHAR(20) NOT NULL, username VARCHAR(100) NOT NULL, avatar_url VARCHAR(200) NOT NULL, score INT UNSIGNED DEFAULT 1, last_save TIMESTAMP DEFAULT NULL);

CREATE TABLE halloween2018timeattack( id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, steam_id VARCHAR(20) NOT NULL, username VARCHAR(100) NOT NULL, score INT UNSIGNED DEFAULT 0, date TIMESTAMP DEFAULT NULL);
